<a href="https://colab.research.google.com/github/karolgacon/data-science-bootcamp/blob/main/NumpyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [8]:
x = np.array([1, 3])
x

array([1, 3])

In [9]:
x.ndim

1

In [10]:
x.shape

(2,)

In [11]:
x.size

2

In [12]:
x.dtype

dtype('int64')

In [14]:
x = np.array([[1,2,3],[4,5,6,]])
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
x.ndim

2

In [16]:
x.shape

(2, 3)

In [17]:
x.size

6

In [18]:
np.zeros(shape=(4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
np.zeros(shape=(4,10), dtype='int')

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [20]:
np.ones(shape=(5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
np.full(shape=(3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [23]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
np.linspace(start=0,stop=50,num=50)

array([ 0.        ,  1.02040816,  2.04081633,  3.06122449,  4.08163265,
        5.10204082,  6.12244898,  7.14285714,  8.16326531,  9.18367347,
       10.20408163, 11.2244898 , 12.24489796, 13.26530612, 14.28571429,
       15.30612245, 16.32653061, 17.34693878, 18.36734694, 19.3877551 ,
       20.40816327, 21.42857143, 22.44897959, 23.46938776, 24.48979592,
       25.51020408, 26.53061224, 27.55102041, 28.57142857, 29.59183673,
       30.6122449 , 31.63265306, 32.65306122, 33.67346939, 34.69387755,
       35.71428571, 36.73469388, 37.75510204, 38.7755102 , 39.79591837,
       40.81632653, 41.83673469, 42.85714286, 43.87755102, 44.89795918,
       45.91836735, 46.93877551, 47.95918367, 48.97959184, 50.        ])

In [27]:
A = np.arange(15)

In [28]:
A.reshape((3,5))

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [29]:
A = np.array([3,1,4,2])
B = np.array([3,-1,3,2])
print(A)
print(B)

[3 1 4 2]
[ 3 -1  3  2]


In [30]:
A+B

array([6, 0, 7, 4])

In [31]:
A-B

array([0, 2, 1, 0])

In [32]:
A*B

array([ 9, -1, 12,  4])

In [33]:
A / B

array([ 1.        , -1.        ,  1.33333333,  1.        ])

In [34]:
A + 3

array([6, 4, 7, 5])

In [35]:
A * 2

array([6, 2, 8, 4])

In [36]:
X = np.array([[1,3],[-2,0]])
Y = np.array([[6,0],[-1,2]])

In [37]:
np.dot(X, Y)

array([[  3,   6],
       [-12,   0]])

In [38]:
np.random.seed(0)

In [43]:
np.random.randn(10,4)

array([[ 0.12167502,  0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297],
       [-1.42001794, -1.70627019,  1.9507754 , -0.50965218],
       [-0.4380743 , -1.25279536,  0.77749036, -1.61389785],
       [-0.21274028, -0.89546656,  0.3869025 , -0.51080514]])

In [44]:
np.random.rand()

0.8209932298479351

In [45]:
np.random.choice([3,2,5,1,5,5])

np.int64(3)

In [46]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [47]:
np.random.shuffle(data)

In [48]:
data

array([5, 9, 7, 6, 3, 0, 8, 4, 2, 1])

In [49]:
np.exp(1)

np.float64(2.718281828459045)

In [50]:
np.sqrt(9)

np.float64(3.0)

In [51]:
np.all([2,3,1])

np.True_

In [52]:
np.any([2,0,0])

np.True_

In [54]:
A = np.random.rand(5)
A

array([0.97958673, 0.35944446, 0.48089353, 0.68866118, 0.88047589])

In [55]:
np.argmax(A)

np.int64(0)

In [56]:
A[np.argmax(A)]

np.float64(0.9795867288127285)

In [57]:
np.argsort(A)

array([1, 2, 3, 4, 0])

In [58]:
np.max(A)

np.float64(0.9795867288127285)

In [59]:
np.mean(A)

np.float64(0.6778123591353158)

In [60]:
np.median(A)

np.float64(0.6886611828057704)

In [61]:
np.std(A)

np.float64(0.23340656169866633)

In [62]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [63]:
A[2]

np.int64(2)

In [64]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [65]:
A[:2]

array([0, 1])

In [66]:
A[[0,2]]

array([0, 2])

In [69]:
A = A.reshape(4,5)
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [75]:
A[:,-1]

array([ 4,  9, 14, 19])

In [76]:
A[1,1]

np.int64(6)

In [77]:
A[1,3]

np.int64(8)

In [79]:
A[1:3,1:4]

array([[ 6,  7,  8],
       [11, 12, 13]])

In [81]:
A[1,2] = 14
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [82]:
for row in A:
    print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [83]:
for row in A:
  print(row[0])

0
5
10
15


In [85]:
for el in A.flat:
  print(el)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [86]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [87]:
A.ravel()

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [88]:
A.T

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

In [89]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1)
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [90]:
A > 0

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [91]:
A[A>0]

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [94]:
np.bitwise_and(A > -5, A < 5)

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [95]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [96]:
np.bitwise_or(A<-5, A>5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [97]:
A[np.bitwise_or(A<-5, A>5)]

array([-10. ,  -9.5,  -9. ,  -8.5,  -8. ,  -7.5,  -7. ,  -6.5,  -6. ,
        -5.5,   5.5,   6. ,   6.5,   7. ,   7.5,   8. ,   8.5,   9. ,
         9.5])